# PR에 라벨이 붙을 경우 검증하는 스크립트이다.
# 해당 PR에 리뷰가 1개 이상 있는지 검증한다.
# 리뷰가 존재할 경우 자동으로 머지를 하고 슬랙봇으로 알람을 보낸다.
name: PR Automerge

on:
  pull_request:
    types: [labeled]
    branches:
      - master
      - service/*

jobs:
  RunTest:
    name: Run Jest
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const refss = "${{github.ref}}"
            const pr_number = Number(refss.split("/")[2])
            const reviews = await github.pulls.listReviews({
              ...context.repo,
              pull_number: pr_number
            })
            if(reviews.data.length <= 0) throw("You need to get other's review!")
            else return true
  CheckLabel:
    runs-on: [ubuntu-latest]
    steps:
      - name: GitHub Script
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            console.log(ref);
            const pr = await github.pulls.get({
              ...context.repo,
              pull_number
            })
            const labels = pr.data.labels;
            console.log(labels);
            const hasAutomerge = labels.some(label=> label.name === "automerge")
            console.log("result is", hasAutomerge)
            if(hasAutomerge){
              github.pulls.merge({
                ...context.repo,
                pull_number
              })
            }
