name: CLIENT DEPLOY

on: 
  push:
    branches:
      - develop/client

jobs:
  DetectPush:
    runs-on: ubuntu-16.04
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: ssh 접속
        uses: appleboy/ssh-action@master
        with:
          host:  ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PWD }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            echo ifconfig
            cd /www/2019-16/client
            echo ${{ secrets.DEV_PWD }} | sudo -S git checkout develop/client
            echo ${{ secrets.DEV_PWD }} | sudo -S git pull
            echo ${{ secrets.DEV_PWD }} | sudo npm install
            echo ${{ secrets.DEV_PWD }} | sudo yarn build && sudo rm -rf ../../build && sudo mv build ../../ && sudo rm -rf node_modules/ package-lock.json
