# 서비스 브랜치에 PR을 보낼 경우 해당 서비스만 테스트를 실행한다.
name: PR Test [Service]

on:
  pull_request:
    types: [opened, reopened]
    branches:
      # - app/*
      - service/*

jobs:
  TestService:
    name: Test Current Service
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: run test
        run: |
          echo base_ref is ${{github.base_ref}}
          echo head_ref is ${{github.head_ref}}
          if [  ${{github.base_ref}} == "service/log" ]
          then
            cd server/services/log
            npm install
            npm test --detectOpenHandles --forceExit
          elif [  ${{github.base_ref}} == "service/analytics" ]
          then
            cd server/services/analytics
            npm install
            npm test --detectOpenHandles --forceExit
          elif [  ${{github.base_ref}} == "service/reservation" ]
          then
            cd server/services/reservation
            npm install
            npm test --detectOpenHandles --forceExit
          elif [  ${{github.base_ref}} == "service/search" ]
          then
            cd server/services/search
            npm install
            npm test --detectOpenHandles --forceExit
          elif [  ${{github.base_ref}} == "service/study_room" ]
          then
            cd server/services/studyroom
            npm install
            npm test --detectOpenHandles --forceExit
          elif [  ${{github.base_ref}} == "service/study_group" ]
          then
            cd server/services/study_group
            npm install
            npm test --detectOpenHandles --forceExit
          elif  [  ${{github.base_ref}} == "service/gateway" ]
          then 
            cd server/api-gateway
            npm install
            npm test --detectOpenHandles --forceExit
          else
            echo Err:Nothing match with your service branch
            return 0
          fi
