# 서비스 브랜치에 PR을 보낼 경우 해당 서비스만 테스트를 실행한다.
name: PR Test [Service]

on:
  pull_request:
    types: [opened, reopened]
    branches:
      # - app/*
      - service/*

jobs:
  TestService:
    name: Test Current Service
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: run test
        run: |
          echo base_ref is ${{github.base_ref}}
          echo head_ref is ${{github.head_ref}}
          if [  ${{github.base_ref}} == "service/log" ]
          then
            cd server/log
            npm install
            npm test
          elif [  ${{github.base_ref}} == "service/analytics" ]
          then
            cd server/analytics
            npm intall
            npm test
          elif [  ${{github.base_ref}} == "service/reservation" ]
          then
            cd server/reservation
            npm intall
            npm test
          elif [  ${{github.base_ref}} == "service/search" ]
          then
            cd server/search
            npm intall
            npm test
          elif [  ${{github.base_ref}} == "service/study_room" ]
          then
            cd server/study_room
            npm intall
            npm test
          elif [  ${{github.base_ref}} == "service/study_group" ]
          then
            cd server/study_group
            npm intall
            npm test
          else
            return 0
          fi
